pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh '''
                    javac -encoding UTF-8 -cp "lib/*" -d classes practice/src/practice/Book.java practice/src/practice/BookManager.java practice/src/practice/main.java practice/src/test/BookManagerTest.java
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                classpath="classes:lib/*:'/Users/eunjung/.jenkins/workspace/SWpractice/lib/JUnit-Platform-Console-1.7.1.jar'"
                java -cp $classpath org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt
                '''
            }
        }
    }

    post {
        always {
            // 테스트 결과 파일을 저장하기 위해 아카이브
            archiveArtifacts 'test_results.txt'
        }

        failure {
            echo 'Build or test failed'
        }

        success {
            echo 'Build and test succeeded'
        }
    }
}
